<a href="https://colab.research.google.com/github/guiabbehusen/ML-PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

2.6.0+cu124


In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
random_tensor = torch.rand(2, 3, 4, 4)
random_tensor

tensor([[[[0.2894, 0.1062, 0.7006, 0.3569],
          [0.3609, 0.8146, 0.0226, 0.7251],
          [0.9147, 0.5936, 0.5245, 0.8949],
          [0.4798, 0.3657, 0.0500, 0.2972]],

         [[0.5961, 0.5284, 0.9861, 0.7386],
          [0.8022, 0.2861, 0.2788, 0.4907],
          [0.1947, 0.5806, 0.3402, 0.8412],
          [0.9955, 0.9487, 0.3339, 0.0293]],

         [[0.7072, 0.2931, 0.5496, 0.4190],
          [0.2323, 0.7662, 0.7365, 0.3563],
          [0.1369, 0.2197, 0.2824, 0.7118],
          [0.4834, 0.6887, 0.6236, 0.0293]]],


        [[[0.5029, 0.4886, 0.5420, 0.9005],
          [0.8447, 0.7750, 0.2616, 0.2592],
          [0.8663, 0.0134, 0.0871, 0.0722],
          [0.3572, 0.1974, 0.5476, 0.0433]],

         [[0.4845, 0.6416, 0.9447, 0.9046],
          [0.0216, 0.3087, 0.4811, 0.2491],
          [0.8939, 0.1425, 0.4847, 0.1729],
          [0.0311, 0.5044, 0.0199, 0.3581]],

         [[0.6714, 0.7642, 0.9336, 0.0842],
          [0.7515, 0.4496, 0.1524, 0.9813],
          [0.6055, 0

In [7]:
tensor_A = torch.tensor([[1, 2, 3],
                         [3, 4, 5]])

In [8]:
tensor_B = torch.tensor([[10, 11, 12],
                         [11, 11, 10]])

In [9]:
print(torch.matmul(tensor_A,tensor_B.T))

tensor([[ 68,  63],
        [134, 127]])


In [10]:
tensor2 = torch.randn(10)
tensor2 = tensor2.int()

In [11]:
tensor2

tensor([ 0,  0, -1,  0,  0,  0,  0,  0,  0,  0], dtype=torch.int32)

In [12]:
x = torch.arange(1., 10.)

In [13]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [14]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [15]:
z = x.view(1, 9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [16]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [17]:
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [18]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])